- defaults:
    link:
        relink: true
        create: true

- link:
    ~/.config/i3/01-local: config/i3/01-local
    ~/.config/bspwm: config/bspwm
    ~/.config/sxhkd: config/sxhkd
    ~/.config/Lemonbar-Helper/config.yaml.base: config/Lemonbar-Helper/config.yaml.base
    ~/.config/compton.conf: config/compton.conf
    ~/.config/mopidy: config/mopidy
    ~/.Xresources: Xresources/Xresources
    ~/.xinitrc-local:
    ~/.zshrc-local:

- shell:
    - [xrdb -merge ~/.Xresources, Merging Xresources]
    - [sh edid.sh, Forcing EDID for broken monitor]
