#!/bin/sh

if [ -f "$userresources" ]; then
    xrdb -I$HOME/.dotfiles/Lemar/Xresources -merge "$userresources"
fi

# Launch Redshift
#redshift -l 52.743142:5.852879 &


# Launch WM
#xsetroot -cursor_name left_ptr &
#sxhkd &
#exec bspwm
exec i3 
