dunst:
    infiles:
        - '~/.config/dunst/dunstrc.base'
        - 'templates/dunstrc.theme'
    outfile: '~/.config/dunst/dunstrc'
    substitute: True

i3:
    infiles: '~/.config/i3/0*'
    outfile: '~/.config/i3/config'
    substitute: False

lemonbar:
    infiles: '~/.config/Lemonbar-Helper/config.yaml.base'
    outfile: '~/.config/Lemonbar-Helper/config.yaml'
    substitute: True

alacritty:
    infiles: 
        - '~/.config/alacritty/alacritty.yml.base'
        - 'templates/alacritty.theme'
    outfile: '~/.config/alacritty/alacritty.yml'
    substitute: True
