#!/bin/sh

if [ -f "$userresources" ]; then
    xrdb -I$HOME/.dotfiles/machines/mEnvy/Xresources -merge "$userresources"
fi

if [ -d "$HOME/.bin" ]; then
    PATH="$HOME/.bin:$PATH"
fi

# Launch Redshift
#redshift -l 52.743142:5.852879 &


# Launch WM
#xsetroot -cursor_name left_ptr &
#sxhkd &
#exec bspwm

#xrandr --dpi 168
# cat ~/.config/i3/0* > ~/.config/i3/config
cd ~/.themes && python reconfigure.py; cd
exec i3 
