#!/bin/sh

if [ -f "$userresources" ]; then
    xrdb -I$HOME/.dotfiles/machines/mEnvy/Xresources -merge "$userresources"
fi

# Launch Redshift
#redshift -l 52.743142:5.852879 &


# Launch WM
#xsetroot -cursor_name left_ptr &
#sxhkd &
#exec bspwm

xrandr --dpi 300
cat ~/.config/i3/0* > ~/.config/i3/config
exec i3 
