#!/bin/zsh
# Configure global vars
export PATH="$PATH:$HOME/.bin:$HOME/.gem/ruby/2.5.0/bin"

export PATH="$PATH:$HOME/src/ESP32/xtensa-esp32-elf/bin"
export IDF_PATH="$HOME/src/ESP32/esp-idf"

# Set theme
antigen theme afowler

# Add base16-shell plugin for 256bit colors
# antigen use chriskempson/base16-shell


# Aliasing
alias arctools='/usr/lib/jvm/java-10-openjdk/bin/java -Dsun.java2d.uiScale=2 -jar ~/Documents/Uni/Module\ 5/ARCTools/ARCToolsv2.1.2.jar'
alias xrdb-update='xrdb -I/home/marten/.dotfiles/machines/mEnvy/Xresources -merge ~/.Xresources'
